### ISSUE TITLE
Not working on modal

### ISSUE THREAD

**Issue by mhinton311** [legalthings/angular-signature#27]
I am able to get the signature-pad directive to work on a normal HTML page. 

However, the directive won't load on a modal form. I've tried using it with $uibModal and $modal services with no luck.

Any ideas?

**Comment by Sarfaraaz** [comment]
We use the directive in a modal ourselves and it works just fine. Please provide a [mcve](http://stackoverflow.com/help/mcve) with your failing use-case in something like jsFiddle.

**Comment by mhinton311** [comment]
I think I see what is going on... for some reason when I use the signature-pad directive on a modal, the canvas width and height are 0.

If I can't figure it out quickly, I will try to put a jsFiddle together later...

**Comment by mcblum** [comment]
@mhinton311 I think that your problem is exactly the same as our problem. In your case, the signature pad is invisible because the modal hasn't opened yet and when it does, it has no height. In our case we have a multi-part form and when a subsequent section is made visible, the height is also set to 0.

**Comment by jasny** [comment]
Should be solved by #28. Can someone please confirm that?

**Comment by mcblum** [comment]
Thank you -- we have put the new version into production and we'll let you know if we continue to see the errors. I appreciate your work on this!
